### ISSUE TITLE
 enable cdn to speed up user visits

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/discourse#2]
https://meta.discourse.org/t/enable-a-cdn-for-your-discourse/14857

**Comment by wangshijun** [comment]
static.community.arcblockio.cn

**Comment by polunzh** [comment]
Enabled:
![image](https://user-images.githubusercontent.com/4244426/71717060-c5900480-2e51-11ea-8a45-54b84f184bf1.png)
